"""Machine-readable catalogue of public measures and their shared cores."""
MEASURE_REGISTRY = {
    "gaussian_entropy": {"domain": "covariance", "analytic": True},
    "mutual_information": {"domain": "covariance", "analytic": True},
    "conditional_mutual_information": {"domain": "covariance", "analytic": True},
    "conditional_covariance": {"domain": "covariance", "analytic": True},
    "total_correlation": {"domain": "covariance", "analytic": True},
    "dual_total_correlation": {"domain": "covariance", "analytic": True},
    "o_information": {"domain": "covariance", "analytic": True},
    "s_information": {"domain": "covariance", "analytic": True},
    "local_gaussian_mi": {"domain": "observations", "analytic": False},
    "autocovariances": {"domain": "var_system", "analytic": True},
    "entropy_rate": {"domain": "var_system", "analytic": True},
    "predictive_information": {"domain": "var_system", "analytic": True},
    "active_information_storage": {"domain": "var_system", "analytic": True},
    "transfer_function": {"domain": "frequency", "analytic": True},
    "inverse_transfer_function": {"domain": "frequency", "analytic": True},
    "cross_spectral_density": {"domain": "frequency", "analytic": True},
    "spectral_entropy": {"domain": "frequency", "analytic": True},
    "spectral_radius": {"domain": "var_system", "analytic": True},
    "stability_margin": {"domain": "var_system", "analytic": True},
    "dominant_timescale": {"domain": "var_system", "analytic": True},
    "covariance_amplification": {"domain": "var_system", "analytic": True},
    "psi": {"domain": "macro_projection", "analytic": True},
    "delta": {"domain": "macro_projection", "analytic": True},
    "gamma": {"domain": "macro_projection", "analytic": True},
    "cmem1_total": {"domain": "var_system", "analytic": True},
    "cmem3_total": {"domain": "var_system", "analytic": True},
    "cmem1_curve": {"domain": "var_system", "analytic": True},
    "cmem3_curve": {"domain": "var_system", "analytic": True},
    "cmem3_lag": {"domain": "var_system", "analytic": True},
    "temporal_mvgc": {"domain": "observations", "analytic": False, "shared_core": "nested_var_models"},
    "spectral_mvgc": {"domain": "observations_frequency", "analytic": False, "shared_core": "nested_var_models"},
    "state_space_temporal_mvgc": {"domain": "innovations_state_space", "analytic": True, "shared_core": "generalized_dare_marginals"},
    "state_space_spectral_mvgc": {"domain": "innovations_state_space_frequency", "analytic": True, "shared_core": "generalized_dare_marginals"},
    "integrate_spectral_mvgc": {"domain": "frequency_curve", "analytic": True},
    "pairwise_spectral_gc": {"domain": "var_system_frequency", "analytic": True},
    "dynamical_dependence": {"domain": "state_space", "analytic": True, "shared_core": "innovations_form"},
    "ssdi": {"domain": "state_space_partition", "analytic": True, "shared_core": "reduced_state_space"},
    "gaussian_phiid_atoms": {"domain": "past_future_covariance", "analytic": True, "atoms": 16, "shared_core": "gaussian_mutual_information"},
    "discrete_entropy": {"domain": "discrete_observations", "analytic": False},
    "discrete_mutual_information": {"domain": "discrete_observations", "analytic": False},
    "discrete_total_correlation": {"domain": "discrete_observations", "analytic": False},
    "lempel_ziv_complexity": {"domain": "discrete_sequence", "analytic": False},
}
