"""Torch-first batched linear-dynamics inference and complexity measures."""

from .adapters import (
    from_complexbox_timeseries,
    from_complexbox_var,
    to_complexbox_timeseries,
    to_complexbox_var,
)
from .control import (
    InnovationsStateSpace,
    ProjectionSearchResult,
    dynamical_dependence,
    innovations_form,
    innovations_transfer_function,
    optimise_dynamical_dependence_projection,
    project_state_space,
    reduce_innovations_state_space,
    reduce_state_space,
    solve_dare,
    solve_generalized_dare,
    stochastic_interaction,
    var_to_innovations_state_space,
)
from .dd_optimization import (
    DDGradientSearchResult,
    innovations_proxy_sequence,
    optimise_dynamical_dependence_proxy,
    optimise_dynamical_dependence_spectral,
    orthonormalise_projection,
    proxy_dynamical_dependence,
    proxy_dynamical_dependence_gradient,
    spectral_dynamical_dependence,
    spectral_dynamical_dependence_gradient,
)
from .measures.primary import (
    ModelMeasureConfig,
    ModelMeasureContext,
    build_measure_context,
    compute_all_model_measures,
    model_autocovariances,
    phiid_from_model,
    spectral_mvgc,
    temporal_mvgc,
)
from .measures.rates import (
    gaussian_instantaneous_information_rate,
    gaussian_mutual_information_rate,
    gaussian_transfer_entropy_rate,
    spectral_gaussian_mutual_information_rate,
    spectral_gaussian_transfer_entropy_rate,
)
from .measures.secondary import (
    WhitenessResult,
    consistency,
    mvgc_pvalue,
    residual_whiteness,
    significance,
)
from .multiscale import (
    downsample_innovations_state_space,
    varma_to_innovations_state_space,
)
from .representations import (
    StateSpaceModel,
    VARSystem,
    build_var_system,
    companion_matrix,
)
from .selection import (
    EpochTimeSeriesSplit,
    StateSpaceOrderScore,
    StateSpaceOrderSearchCV,
    StateSpaceOrderSearchResult,
    StateSpaceOrderSelection,
    StateSpaceOrderSelectionResult,
    VARInformationCriteriaResult,
    VAROrderScore,
    VAROrderSearchCV,
    VAROrderSearchResult,
    VAROrderSelectionIC,
)
from .simulate import (
    automatic_burnin,
    demo_var,
    random_correlation_matrix,
    random_positive_definite_covariance,
    random_stable_var,
    simulate_var,
)
from .spectra import innovations_spectral_density, integrate_spectral_rate
from .state_space import (
    N4SID,
    LarimoreStateSpace,
    LinearGaussianEM,
    kalman_filter,
    kalman_smoother,
)
from .var import VAR, VARParameters

__all__ = [
    "DDGradientSearchResult",
    "N4SID",
    "VAR",
    "EpochTimeSeriesSplit",
    "InnovationsStateSpace",
    "LarimoreStateSpace",
    "LinearGaussianEM",
    "ModelMeasureConfig",
    "ModelMeasureContext",
    "ProjectionSearchResult",
    "StateSpaceModel",
    "StateSpaceOrderScore",
    "StateSpaceOrderSearchCV",
    "StateSpaceOrderSearchResult",
    "StateSpaceOrderSelection",
    "StateSpaceOrderSelectionResult",
    "VARInformationCriteriaResult",
    "VAROrderScore",
    "VAROrderSearchCV",
    "VAROrderSearchResult",
    "VAROrderSelectionIC",
    "VARParameters",
    "VARSystem",
    "WhitenessResult",
    "automatic_burnin",
    "build_measure_context",
    "build_var_system",
    "companion_matrix",
    "compute_all_model_measures",
    "consistency",
    "demo_var",
    "downsample_innovations_state_space",
    "dynamical_dependence",
    "from_complexbox_timeseries",
    "from_complexbox_var",
    "gaussian_instantaneous_information_rate",
    "gaussian_mutual_information_rate",
    "gaussian_transfer_entropy_rate",
    "innovations_form",
    "innovations_proxy_sequence",
    "innovations_spectral_density",
    "innovations_transfer_function",
    "integrate_spectral_rate",
    "kalman_filter",
    "kalman_smoother",
    "model_autocovariances",
    "mvgc_pvalue",
    "optimise_dynamical_dependence_projection",
    "optimise_dynamical_dependence_proxy",
    "optimise_dynamical_dependence_spectral",
    "orthonormalise_projection",
    "phiid_from_model",
    "project_state_space",
    "proxy_dynamical_dependence",
    "proxy_dynamical_dependence_gradient",
    "random_correlation_matrix",
    "random_positive_definite_covariance",
    "random_stable_var",
    "reduce_innovations_state_space",
    "reduce_state_space",
    "residual_whiteness",
    "significance",
    "simulate_var",
    "solve_dare",
    "solve_generalized_dare",
    "spectral_dynamical_dependence",
    "spectral_dynamical_dependence_gradient",
    "spectral_gaussian_mutual_information_rate",
    "spectral_gaussian_transfer_entropy_rate",
    "spectral_mvgc",
    "stochastic_interaction",
    "temporal_mvgc",
    "to_complexbox_timeseries",
    "to_complexbox_var",
    "var_to_innovations_state_space",
    "varma_to_innovations_state_space",
]
__version__ = "0.8.0"
