"""Torch-first batched linear-dynamics inference and complexity measures."""

from .adapters import (
    from_complexbox_timeseries,
    from_complexbox_var,
    to_complexbox_timeseries,
    to_complexbox_var,
)
from .control import (
    InnovationsStateSpace,
    ProjectionSearchResult,
    dynamical_dependence,
    innovations_form,
    innovations_transfer_function,
    optimise_dynamical_dependence_projection,
    project_state_space,
    reduce_innovations_state_space,
    reduce_state_space,
    solve_dare,
    solve_generalized_dare,
    stochastic_interaction,
    var_to_innovations_state_space,
)
from .dd import (
    DDObjective,
    DDOptimizationResult,
    DDSSDIOptimizationResult,
    DDOptimizer,
    optimise_dynamical_dependence,
)
from .dd_optimization import (
    DDGradientSearchResult,
    innovations_proxy_sequence,
    optimise_dynamical_dependence_proxy,
    optimise_dynamical_dependence_spectral,
    orthonormalise_projection,
    proxy_dynamical_dependence,
    proxy_dynamical_dependence_gradient,
    spectral_dynamical_dependence,
    spectral_dynamical_dependence_gradient,
)
from .measures.hop import HOPResult, SpectralHOPResult, hop_analysis, spectral_hop_analysis
from .measures.oir import (
    delta_o_information_rate,
    o_information_rate,
    spectral_delta_o_information_rate,
    spectral_o_information_rate,
)
from .measures.pdgc import (
    PDGCResult,
    SpectralPDGCResult,
    partial_granger_causality_decomposition,
    spectral_partial_granger_causality_decomposition,
)
from .measures.phid_primary import phiid_redundancy_from_model
from .measures.pird import (
    PIRDResult,
    SpectralPIRDResult,
    partial_information_rate_decomposition,
    spectral_partial_information_rate_decomposition,
)
from .measures.primary import (
    ModelMeasureConfig,
    ModelMeasureContext,
    build_measure_context,
    compute_all_model_measures,
    model_autocovariances,
    phiid_from_model,
    spectral_mvgc,
    temporal_mvgc,
)
from .measures.rates import (
    gaussian_instantaneous_information_rate,
    gaussian_mutual_information_rate,
    gaussian_transfer_entropy_rate,
    spectral_gaussian_mutual_information_rate,
    spectral_gaussian_transfer_entropy_rate,
)
from .measures.secondary import (
    WhitenessResult,
    consistency,
    mvgc_pvalue,
    residual_whiteness,
    significance,
)
from .multiscale import (
    downsample_innovations_state_space,
    varma_to_innovations_state_space,
)
from .representations import (
    StateSpaceModel,
    VARSystem,
    build_var_system,
    companion_matrix,
)
from .selection import (
    EpochTimeSeriesSplit,
    StateSpaceOrderScore,
    StateSpaceOrderSearchCV,
    StateSpaceOrderSearchResult,
    StateSpaceOrderSelection,
    StateSpaceOrderSelectionResult,
    VARInformationCriteriaResult,
    VAROrderScore,
    VAROrderSearchCV,
    VAROrderSearchResult,
    VAROrderSelectionIC,
)
from .simulate import (
    automatic_burnin,
    demo_var,
    random_correlation_matrix,
    random_positive_definite_covariance,
    random_stable_var,
    simulate_var,
)
from .spectra import innovations_spectral_density, integrate_spectral_rate
from .state_space import (
    N4SID,
    LarimoreStateSpace,
    LinearGaussianEM,
    kalman_filter,
    kalman_smoother,
)
from .synthetic import (
    SYNTHETIC_SYSTEMS,
    SYNTHETIC_SYSTEM_PARAMETERS,
    available_synthetic_systems,
    equicorrelated_innovation_covariance,
    planted_module_projection,
    synthetic_system_parameters,
    synthetic_transition_matrix,
    synthetic_var,
)
from .var import VAR, VARParameters

__all__ = [
    "DDGradientSearchResult",
    "DDObjective",
    "DDOptimizationResult",
    "DDSSDIOptimizationResult",
    "DDOptimizer",
    "HOPResult",
    "N4SID",
    "PDGCResult",
    "PIRDResult",
    "SYNTHETIC_SYSTEMS",
    "SYNTHETIC_SYSTEM_PARAMETERS",
    "SpectralHOPResult",
    "SpectralPDGCResult",
    "SpectralPIRDResult",
    "VAR",
    "EpochTimeSeriesSplit",
    "InnovationsStateSpace",
    "LarimoreStateSpace",
    "LinearGaussianEM",
    "ModelMeasureConfig",
    "ModelMeasureContext",
    "ProjectionSearchResult",
    "StateSpaceModel",
    "StateSpaceOrderScore",
    "StateSpaceOrderSearchCV",
    "StateSpaceOrderSearchResult",
    "StateSpaceOrderSelection",
    "StateSpaceOrderSelectionResult",
    "VARInformationCriteriaResult",
    "VAROrderScore",
    "VAROrderSearchCV",
    "VAROrderSearchResult",
    "VAROrderSelectionIC",
    "VARParameters",
    "VARSystem",
    "WhitenessResult",
    "automatic_burnin",
    "available_synthetic_systems",
    "build_measure_context",
    "build_var_system",
    "companion_matrix",
    "compute_all_model_measures",
    "consistency",
    "delta_o_information_rate",
    "demo_var",
    "downsample_innovations_state_space",
    "dynamical_dependence",
    "equicorrelated_innovation_covariance",
    "from_complexbox_timeseries",
    "from_complexbox_var",
    "gaussian_instantaneous_information_rate",
    "gaussian_mutual_information_rate",
    "gaussian_transfer_entropy_rate",
    "hop_analysis",
    "innovations_form",
    "innovations_proxy_sequence",
    "innovations_spectral_density",
    "innovations_transfer_function",
    "integrate_spectral_rate",
    "kalman_filter",
    "kalman_smoother",
    "model_autocovariances",
    "mvgc_pvalue",
    "o_information_rate",
    "optimise_dynamical_dependence",
    "optimise_dynamical_dependence_projection",
    "optimise_dynamical_dependence_proxy",
    "optimise_dynamical_dependence_spectral",
    "orthonormalise_projection",
    "partial_granger_causality_decomposition",
    "partial_information_rate_decomposition",
    "phiid_from_model",
    "phiid_redundancy_from_model",
    "planted_module_projection",
    "project_state_space",
    "proxy_dynamical_dependence",
    "proxy_dynamical_dependence_gradient",
    "random_correlation_matrix",
    "random_positive_definite_covariance",
    "random_stable_var",
    "reduce_innovations_state_space",
    "reduce_state_space",
    "residual_whiteness",
    "significance",
    "simulate_var",
    "solve_dare",
    "solve_generalized_dare",
    "spectral_delta_o_information_rate",
    "spectral_dynamical_dependence",
    "spectral_dynamical_dependence_gradient",
    "spectral_gaussian_mutual_information_rate",
    "spectral_gaussian_transfer_entropy_rate",
    "spectral_hop_analysis",
    "spectral_mvgc",
    "spectral_o_information_rate",
    "spectral_partial_granger_causality_decomposition",
    "spectral_partial_information_rate_decomposition",
    "stochastic_interaction",
    "synthetic_system_parameters",
    "synthetic_transition_matrix",
    "synthetic_var",
    "temporal_mvgc",
    "to_complexbox_timeseries",
    "to_complexbox_var",
    "var_to_innovations_state_space",
    "varma_to_innovations_state_space",
]
__version__ = "0.8.0"
