r"""Resampling-based confidence intervals for model-derived VAR measures.

This module generalizes the ARres strategy of Beda, Simpson, and Faes from
univariate autoregressive models to ComplexTorch's multivariate VAR contract.
The fitted model order is held fixed, synthetic trajectories are generated by
residual bootstrap or Gaussian parametric Monte Carlo, and all requested
model-derived measures are evaluated from one shared batched ensemble of
refitted :class:`~complextorch.VARSystem` objects.

Dynamical dependence is evaluated only for a user-supplied fixed projection (or
one supplied projection per independent trajectory). Projection optimization is
intentionally never performed inside the resampling loop.

References
----------
- Beda, A., Simpson, D. M., and Faes, L. (2017). Estimation of confidence
  limits for descriptive indexes derived from autoregressive analysis of time
  series: methods and application to heart rate variability. *PLoS ONE*,
  12(10), e0186694.
- Lütkepohl, H. (2005). *New Introduction to Multiple Time Series Analysis*.
"""
from __future__ import annotations

import copy
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, replace
from typing import Any, Literal

import numpy as np
import torch

from .measures.primary import ModelMeasureConfig, compute_all_model_measures
from .representations import VARSystem, build_var_system, companion_matrix
from .var import VAR

ResamplingMethod = Literal["residual_bootstrap", "parametric"]


@dataclass(frozen=True)
class MeasureInterval:
    """Point estimate and percentile confidence limits for one measure."""

    estimate: torch.Tensor
    lower: torch.Tensor
    upper: torch.Tensor
    samples: torch.Tensor | None
    n_valid: int


@dataclass(frozen=True)
class ConfidenceIntervalResult:
    """Confidence intervals obtained from one shared VAR resampling ensemble."""

    intervals: Mapping[str, MeasureInterval]
    method: ResamplingMethod
    confidence: float
    n_resamples: int
    n_valid: int
    n_failed: int
    seed: int | None
    var_order: int
    fit_mode: str

    def __getitem__(self, name: str) -> MeasureInterval:
        """Return one named interval."""
        return self.intervals[name]


def _normalise_trials(estimator: VAR, x: np.ndarray | torch.Tensor) -> torch.Tensor:
    """Normalize observations through the VAR estimator input contract."""
    return estimator._normalise_input(x)  # noqa: SLF001 - shared estimator contract


def _prediction_residuals(estimator: VAR, trials: torch.Tensor) -> torch.Tensor:
    """Return within-trajectory one-step residual vectors."""
    return trials[:, estimator.order :, :] - estimator.one_step_predictions(trials)


def _draw_innovations(
    residuals: torch.Tensor,
    covariance: torch.Tensor,
    *,
    mode: str,
    method: ResamplingMethod,
    n_resamples: int,
    generator: torch.Generator,
) -> torch.Tensor:
    """Draw innovation vectors while preserving zero-lag multivariate structure."""
    batch, length, n_variables = residuals.shape
    if method == "residual_bootstrap":
        if mode == "pooled":
            pool = residuals.reshape(batch * length, n_variables)
            pool = pool - pool.mean(dim=0, keepdim=True)
            index = torch.randint(
                pool.shape[0], (n_resamples, batch, length),
                device=residuals.device, generator=generator,
            )
            return pool[index]
        centered = residuals - residuals.mean(dim=1, keepdim=True)
        index = torch.randint(
            length, (n_resamples, batch, length),
            device=residuals.device, generator=generator,
        )
        expanded = centered.unsqueeze(0).expand(n_resamples, -1, -1, -1)
        return torch.gather(
            expanded, 2,
            index.unsqueeze(-1).expand(-1, -1, -1, n_variables),
        )
    if method != "parametric":
        raise ValueError("method must be 'residual_bootstrap' or 'parametric'")
    covariance = covariance if covariance.ndim == 3 else covariance.unsqueeze(0)
    if mode == "pooled":
        covariance = covariance.expand(batch, -1, -1)
    elif covariance.shape[0] != batch:
        raise ValueError("independent VAR covariance batch does not match trajectories")
    chol = torch.linalg.cholesky(covariance)
    standard = torch.randn(
        (n_resamples, batch, length, n_variables),
        dtype=residuals.dtype, device=residuals.device, generator=generator,
    )
    return torch.einsum("rbtn,bmn->rbtm", standard, chol)


def _simulate_resamples(
    trials: torch.Tensor,
    estimator: VAR,
    innovations: torch.Tensor,
) -> torch.Tensor:
    """Simulate all resamples in parallel over resample and trajectory axes."""
    n_resamples, batch, length, n_variables = innovations.shape
    order = estimator.order
    output = torch.empty(
        (n_resamples, batch, trials.shape[1], n_variables),
        dtype=trials.dtype, device=trials.device,
    )
    output[:, :, :order, :] = trials[None, :, :order, :]
    coefficients = estimator.coef_
    intercept = estimator.intercept_
    if estimator.mode == "pooled":
        coefficients = coefficients.expand(batch, -1, -1, -1)
        intercept = intercept.expand(batch, -1)
    elif coefficients.shape[0] != batch:
        raise ValueError("independent fitted VAR batch does not match trajectories")
    # The time recursion is sequential by definition; resamples/trials stay batched.
    for offset in range(length):
        time = order + offset
        previous = torch.stack(
            [output[:, :, time - lag, :] for lag in range(1, order + 1)], dim=-2
        )
        prediction = torch.einsum("rbps,bpns->rbn", previous, coefficients)
        output[:, :, time, :] = (
            prediction + intercept.unsqueeze(0) + innovations[:, :, offset, :]
        )
    return output


def _batched_ols_refit(
    samples: torch.Tensor,
    estimator: VAR,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Refit all synthetic VARs without creating cross-trajectory lag rows."""
    n_resamples, batch, time, n_variables = samples.shape
    order = estimator.order
    length = time - order
    design = torch.cat(
        [samples[:, :, order - lag : time - lag, :] for lag in range(1, order + 1)],
        dim=-1,
    )
    targets = samples[:, :, order:, :]
    if estimator.fit_intercept:
        design = torch.cat(
            [design, torch.ones((*design.shape[:-1], 1), dtype=design.dtype, device=design.device)],
            dim=-1,
        )
    if estimator.mode == "pooled":
        design_fit = design.reshape(n_resamples, batch * length, -1)
        targets_fit = targets.reshape(n_resamples, batch * length, n_variables)
        output_batch, nfit = n_resamples, batch * length
    elif estimator.mode == "independent":
        design_fit = design.reshape(n_resamples * batch, length, -1)
        targets_fit = targets.reshape(n_resamples * batch, length, n_variables)
        output_batch, nfit = n_resamples * batch, length
    else:
        raise ValueError("mode must be 'pooled' or 'independent'")
    solution = torch.linalg.lstsq(design_fit, targets_fit).solution
    coefficient_flat = solution[:, :-1, :] if estimator.fit_intercept else solution
    coefficients = coefficient_flat.reshape(
        output_batch, order, n_variables, n_variables
    ).transpose(-1, -2)
    residuals = targets_fit - design_fit @ solution
    denominator = nfit if estimator.covariance == "mle" else nfit - design_fit.shape[-1]
    if denominator <= 0:
        raise ValueError("not enough observations for resampled VAR covariance")
    covariance = residuals.transpose(-1, -2) @ residuals / float(denominator)
    return coefficients, 0.5 * (covariance + covariance.transpose(-1, -2))


def _stable_resample_mask(
    coefficients: torch.Tensor,
    *,
    n_resamples: int,
    n_trials: int,
    mode: str,
) -> torch.Tensor:
    """Return a common resample mask containing only stationary fitted VARs."""
    radius = torch.linalg.eigvals(companion_matrix(coefficients)).abs().amax(dim=-1)
    if mode == "pooled":
        return radius < 1
    return (radius.reshape(n_resamples, n_trials) < 1).all(dim=1)


def _build_ensemble(
    coefficients: torch.Tensor,
    covariance: torch.Tensor,
    valid: torch.Tensor,
    *,
    n_resamples: int,
    n_trials: int,
    mode: str,
) -> VARSystem:
    """Build one canonical batched VARSystem from all valid resamples."""
    if mode == "pooled":
        return build_var_system(coefficients[valid], covariance[valid])
    coefficients = coefficients.reshape(n_resamples, n_trials, *coefficients.shape[1:])
    covariance = covariance.reshape(n_resamples, n_trials, *covariance.shape[1:])
    return build_var_system(
        coefficients[valid].reshape(-1, *coefficients.shape[2:]),
        covariance[valid].reshape(-1, *covariance.shape[2:]),
    )


def _ensemble_config(
    config: ModelMeasureConfig,
    *,
    n_valid: int,
    n_trials: int,
    mode: str,
) -> ModelMeasureConfig:
    """Broadcast supplied fixed macro projections over the resample axis."""
    projection = config.macro_projection
    if projection is None or projection.ndim == 2:
        return config
    if projection.ndim != 3:
        raise ValueError("macro_projection must have shape (m,n) or (batch,m,n)")
    if mode == "pooled":
        if projection.shape[0] != 1:
            raise ValueError("pooled inference accepts one fixed macro projection")
        return replace(config, macro_projection=projection.expand(n_valid, -1, -1))
    if projection.shape[0] != n_trials:
        raise ValueError("independent inference requires one projection per trajectory")
    expanded = projection.unsqueeze(0).expand(n_valid, -1, -1, -1)
    return replace(
        config,
        macro_projection=expanded.reshape(n_valid * n_trials, *projection.shape[1:]),
    )


def _flatten_tensor_measures(value: Any, prefix: str = "") -> dict[str, torch.Tensor]:
    """Flatten nested measure dictionaries while ignoring metadata/context objects."""
    if torch.is_tensor(value):
        return {prefix: value} if prefix else {}
    output: dict[str, torch.Tensor] = {}
    if isinstance(value, Mapping):
        for key, child in value.items():
            if key in {"context", "available", "not_available", "model_type"}:
                continue
            name = f"{prefix}.{key}" if prefix else str(key)
            output.update(_flatten_tensor_measures(child, name))
    return output


def _resolve_measure_names(
    available: Mapping[str, torch.Tensor],
    requested: str | Sequence[str],
) -> tuple[str, ...]:
    """Resolve exact measure paths or unique final-component aliases."""
    if requested == "all_compatible":
        return tuple(sorted(available))
    raw = (requested,) if isinstance(requested, str) else tuple(requested)
    resolved: list[str] = []
    for name in raw:
        if name in available:
            resolved.append(name)
            continue
        matches = [path for path in available if path.rsplit(".", 1)[-1] == name]
        if len(matches) == 1:
            resolved.append(matches[0])
        elif not matches:
            raise ValueError(f"unknown or unavailable measure: {name}")
        else:
            raise ValueError(f"ambiguous measure name {name!r}; use one of {matches}")
    return tuple(dict.fromkeys(resolved))


def measure_confidence_intervals(
    X: np.ndarray | torch.Tensor,
    measures: str | Sequence[str] = "all_compatible",
    *,
    var: VAR | None = None,
    config: ModelMeasureConfig | None = None,
    method: ResamplingMethod = "residual_bootstrap",
    n_resamples: int = 1000,
    confidence: float = 0.95,
    seed: int | None = None,
    return_samples: bool = False,
) -> ConfidenceIntervalResult:
    r"""Estimate percentile confidence intervals from one shared VAR ensemble.

    The observed series is fitted once. Every synthetic realization is generated
    from that fit and refitted at the same fixed VAR order. ComplexTorch then
    evaluates the complete compatible primary-measure tree once on the shared
    batched ensemble; selecting one or many ``measures`` never repeats the
    resampling or the VAR refits.

    Parameters
    ----------
    X
        Observations shaped ``(time, variables)`` or ``(batch, time, variables)``.
    measures
        ``"all_compatible"``, a flattened path such as
        ``"gaussian.o_information"``, a unique leaf alias such as
        ``"o_information"``, or a sequence of names.
    var
        Fixed-order VAR estimator. If omitted, ``VAR(order=1, mode="pooled")``.
        The supplied estimator is copied before fitting. This initial
        implementation supports unregularized OLS estimators; ``solver='lwr'``
        is rejected explicitly.
    config
        Primary-measure configuration. ``macro_projection`` is fixed throughout
        inference and is never optimized. In independent mode it may be either
        one shared 2-D projection or one 3-D projection per trajectory.
    method
        Residual-vector bootstrap or Gaussian parametric Monte Carlo.
    n_resamples
        Number of requested synthetic VAR refits.
    confidence
        Central percentile confidence level in ``(0,1)``.
    seed
        Optional local Torch RNG seed.
    return_samples
        Retain the resampled measure values when true.

    Returns
    -------
    ConfidenceIntervalResult
        Point estimates, percentile limits, and resampling diagnostics.

    Notes
    -----
    Resampled unstable VARs are excluded and counted. For independent fitting a
    resample is retained only if every trajectory-specific VAR is stable, giving
    all original trajectories the same bootstrap-resample axis.
    """
    if n_resamples < 2:
        raise ValueError("n_resamples must be at least two")
    if not 0 < confidence < 1:
        raise ValueError("confidence must lie strictly between zero and one")
    estimator = copy.deepcopy(VAR(order=1, mode="pooled") if var is None else var)
    if estimator.alpha != 0:
        raise ValueError("ARres inference currently requires an unregularized VAR")
    if estimator.solver == "lwr":
        raise ValueError("ARres inference currently supports OLS VAR estimators, not solver='lwr'")
    trials = _normalise_trials(estimator, X)
    estimator.fit(trials)
    residuals = _prediction_residuals(estimator, trials)
    generator = torch.Generator(device=trials.device)
    if seed is not None:
        generator.manual_seed(seed)
    innovations = _draw_innovations(
        residuals, estimator.noise_covariance_, mode=estimator.mode,
        method=method, n_resamples=n_resamples, generator=generator,
    )
    synthetic = _simulate_resamples(trials, estimator, innovations)
    coefficients, covariance = _batched_ols_refit(synthetic, estimator)
    valid = _stable_resample_mask(
        coefficients, n_resamples=n_resamples, n_trials=trials.shape[0], mode=estimator.mode
    )
    n_valid = int(valid.sum().item())
    if n_valid < 2:
        raise RuntimeError("fewer than two stable resampled VARs remain")
    ensemble = _build_ensemble(
        coefficients, covariance, valid, n_resamples=n_resamples,
        n_trials=trials.shape[0], mode=estimator.mode,
    )
    original_system = build_var_system(estimator.coef_, estimator.noise_covariance_)
    measure_config = ModelMeasureConfig() if config is None else config
    original_flat = _flatten_tensor_measures(
        compute_all_model_measures(original_system, measure_config)
    )
    ensemble_flat = _flatten_tensor_measures(
        compute_all_model_measures(
            ensemble,
            _ensemble_config(
                measure_config, n_valid=n_valid, n_trials=trials.shape[0], mode=estimator.mode
            ),
        )
    )
    names = _resolve_measure_names(original_flat, measures)
    missing = [name for name in names if name not in ensemble_flat]
    if missing:
        raise RuntimeError(f"measures unavailable on bootstrap ensemble: {missing}")
    alpha = (1.0 - confidence) / 2.0
    intervals: dict[str, MeasureInterval] = {}
    for name in names:
        estimate, samples = original_flat[name], ensemble_flat[name]
        if estimator.mode == "pooled":
            if samples.shape[0] != n_valid:
                raise RuntimeError(f"measure {name} does not preserve the VAR batch axis")
            estimate = estimate[0] if estimate.shape[:1] == (1,) else estimate
            sample_view = samples
        else:
            expected = n_valid * trials.shape[0]
            if samples.shape[0] != expected:
                raise RuntimeError(f"measure {name} does not preserve the VAR batch axis")
            sample_view = samples.reshape(n_valid, trials.shape[0], *samples.shape[1:])
        intervals[name] = MeasureInterval(
            estimate=estimate,
            lower=torch.quantile(sample_view, alpha, dim=0),
            upper=torch.quantile(sample_view, 1.0 - alpha, dim=0),
            samples=sample_view if return_samples else None,
            n_valid=n_valid,
        )
    return ConfidenceIntervalResult(
        intervals=intervals, method=method, confidence=confidence,
        n_resamples=n_resamples, n_valid=n_valid, n_failed=n_resamples - n_valid,
        seed=seed, var_order=estimator.order, fit_mode=estimator.mode,
    )


__all__ = [
    "ConfidenceIntervalResult",
    "MeasureInterval",
    "ResamplingMethod",
    "measure_confidence_intervals",
]
