r"""Resampling-based confidence intervals for model-derived VAR measures.

This module generalizes the ARres strategy of Beda, Simpson, and Faes from
univariate autoregressive models to ComplexTorch's multivariate VAR contract.
An observed VAR is fitted once, many synthetic trajectories are generated by
residual bootstrap or Gaussian parametric Monte Carlo, the VAR is refitted for
every resample, and all requested model-derived measures are evaluated from one
shared batched ensemble of fitted :class:`~complextorch.VARSystem` objects.

The model order is held fixed during resampling. Dynamical dependence is always
computed for the supplied ``ModelMeasureConfig.macro_projection``; projection
optimization is intentionally outside the inference loop.

References
----------
- Beda, A., Simpson, D. M., and Faes, L. (2017). Estimation of confidence
  limits for descriptive indexes derived from autoregressive analysis of time
  series: methods and application to heart rate variability. *PLoS ONE*,
  12(10), e0186694.
- Lütkepohl, H. (2005). *New Introduction to Multiple Time Series Analysis*.
"""
from __future__ import annotations

import copy
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, replace
from typing import Any, Literal

import numpy as np
import torch

from .measures.primary import ModelMeasureConfig, compute_all_model_measures
from .representations import VARSystem, build_var_system, companion_matrix
from .var import VAR

ResamplingMethod = Literal["residual_bootstrap", "parametric"]


@dataclass(frozen=True)
class MeasureInterval:
    """Point estimate and percentile confidence limits for one measure."""

    estimate: torch.Tensor
    lower: torch.Tensor
    upper: torch.Tensor
    samples: torch.Tensor | None
    n_valid: int


@dataclass(frozen=True)
class ConfidenceIntervalResult:
    """Confidence intervals obtained from one shared VAR resampling ensemble."""

    intervals: Mapping[str, MeasureInterval]
    method: ResamplingMethod
    confidence: float
    n_resamples: int
    n_valid: int
    n_failed: int
    seed: int | None
    var_order: int
    fit_mode: str

    def __getitem__(self, name: str) -> MeasureInterval:
        """Return one named interval."""
        return self.intervals[name]


def _normalise_trials(estimator: VAR, x: np.ndarray | torch.Tensor) -> torch.Tensor:
    """Normalize observations through the estimator's public input contract."""
    return estimator._normalise_input(x)  # noqa: SLF001 - shared estimator contract


def _prediction_residuals(estimator: VAR, trials: torch.Tensor) -> torch.Tensor:
    """Return within-trajectory one-step residual vectors."""
    predictions = estimator.one_step_predictions(trials)
    targets = trials[:, estimator.order :, :]
    return targets - predictions


def _draw_innovations(
    residuals: torch.Tensor,
    covariance: torch.Tensor,
    *,
    mode: str,
    method: ResamplingMethod,
    n_resamples: int,
    generator: torch.Generator,
) -> torch.Tensor:
    """Draw complete innovation vectors without breaking contemporaneous covariance."""
    batch, length, n_variables = residuals.shape
    if method == "residual_bootstrap":
        if mode == "pooled":
            pool = residuals.reshape(batch * length, n_variables)
            pool = pool - pool.mean(dim=0, keepdim=True)
            index = torch.randint(
                pool.shape[0],
                (n_resamples, batch, length),
                device=residuals.device,
                generator=generator,
            )
            return pool[index]
        centered = residuals - residuals.mean(dim=1, keepdim=True)
        index = torch.randint(
            length,
            (n_resamples, batch, length),
            device=residuals.device,
            generator=generator,
        )
        expanded = centered.unsqueeze(0).expand(n_resamples, -1, -1, -1)
        return torch.gather(
            expanded,
            2,
            index.unsqueeze(-1).expand(-1, -1, -1, n_variables),
        )
    if method != "parametric":
        raise ValueError("method must be 'residual_bootstrap' or 'parametric'")
    covariance = covariance if covariance.ndim == 3 else covariance.unsqueeze(0)
    if mode == "pooled":
        covariance = covariance.expand(batch, -1, -1)
    elif covariance.shape[0] != batch:
        raise ValueError("independent VAR covariance batch does not match trajectories")
    chol = torch.linalg.cholesky(covariance)
    standard = torch.randn(
        (n_resamples, batch, length, n_variables),
        dtype=residuals.dtype,
        device=residuals.device,
        generator=generator,
    )
    return standard @ chol.transpose(-1, -2).unsqueeze(0).unsqueeze(2)


def _simulate_resamples(
    trials: torch.Tensor,
    estimator: VAR,
    innovations: torch.Tensor,
) -> torch.Tensor:
    """Simulate bootstrap trajectories in parallel over resamples and trials."""
    n_resamples, batch, length, n_variables = innovations.shape
    order = estimator.order
    output = torch.empty(
        (n_resamples, batch, trials.shape[1], n_variables),
        dtype=trials.dtype,
        device=trials.device,
    )
    output[:, :, :order, :] = trials.unsqueeze(0)[:, :, :order, :]
    coefficients = estimator.coef_
    intercept = estimator.intercept_
    if estimator.mode == "pooled":
        coefficients = coefficients.expand(batch, -1, -1, -1)
        intercept = intercept.expand(batch, -1)
    elif coefficients.shape[0] != batch:
        raise ValueError("independent fitted VAR batch does not match trajectories")
    for offset in range(length):
        time = order + offset
        previous = torch.stack(
            [output[:, :, time - lag, :] for lag in range(1, order + 1)],
            dim=-2,
        )
        prediction = torch.einsum("rbps,bpns->rbn", previous, coefficients)
        output[:, :, time, :] = prediction + intercept.unsqueeze(0) + innovations[:, :, offset, :]
    return output


def _batched_ols_refit(
    samples: torch.Tensor,
    estimator: VAR,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Refit all resampled VARs without constructing lags across trajectories."""
    n_resamples, batch, time, n_variables = samples.shape
    order = estimator.order
    length = time - order
    design = torch.cat(
        [samples[:, :, order - lag : time - lag, :] for lag in range(1, order + 1)],
        dim=-1,
    )
    targets = samples[:, :, order:, :]
    if estimator.fit_intercept:
        ones = torch.ones(
            (*design.shape[:-1], 1), dtype=design.dtype, device=design.device
        )
        design = torch.cat([design, ones], dim=-1)
    if estimator.mode == "pooled":
        design_fit = design.reshape(n_resamples, batch * length, -1)
        targets_fit = targets.reshape(n_resamples, batch * length, n_variables)
        output_batch = n_resamples
        nfit = batch * length
    elif estimator.mode == "independent":
        design_fit = design.reshape(n_resamples * batch, length, -1)
        targets_fit = targets.reshape(n_resamples * batch, length, n_variables)
        output_batch = n_resamples * batch
        nfit = length
    else:
        raise ValueError("mode must be 'pooled' or 'independent'")
    solution = torch.linalg.lstsq(design_fit, targets_fit).solution
    if estimator.fit_intercept:
        coefficient_flat = solution[:, :-1, :]
    else:
        coefficient_flat = solution
    coefficients = coefficient_flat.reshape(
        output_batch, order, n_variables, n_variables
    ).transpose(-1, -2)
    residuals = targets_fit - design_fit @ solution
    predictors = design_fit.shape[-1]
    denominator = nfit if estimator.covariance == "mle" else nfit - predictors
    if denominator <= 0:
        raise ValueError("not enough observations for resampled VAR covariance")
    covariance = residuals.transpose(-1, -2) @ residuals / float(denominator)
    covariance = 0.5 * (covariance + covariance.transpose(-1, -2))
    return coefficients, covariance


def _stable_resample_mask(
    coefficients: torch.Tensor,
    *,
    n_resamples: int,
    n_trials: int,
    mode: str,
) -> torch.Tensor:
    """Return resamples whose fitted VAR systems are stationary."""
    radius = torch.linalg.eigvals(companion_matrix(coefficients)).abs().amax(dim=-1)
    if mode == "pooled":
        return radius < 1
    return (radius.reshape(n_resamples, n_trials) < 1).all(dim=1)


def _build_ensemble(
    coefficients: torch.Tensor,
    covariance: torch.Tensor,
    valid: torch.Tensor,
    *,
    n_resamples: int,
    n_trials: int,
    mode: str,
) -> VARSystem:
    """Build one canonical batched VAR ensemble from all valid resamples."""
    if mode == "pooled":
        return build_var_system(coefficients[valid], covariance[valid])
    coefficient_view = coefficients.reshape(n_resamples, n_trials, *coefficients.shape[1:])
    covariance_view = covariance.reshape(n_resamples, n_trials, *covariance.shape[1:])
    selected_coefficients = coefficient_view[valid].reshape(-1, *coefficients.shape[1:])
    selected_covariance = covariance_view[valid].reshape(-1, *covariance.shape[1:])
    return build_var_system(selected_coefficients, selected_covariance)


def _ensemble_config(
    config: ModelMeasureConfig,
    *,
    n_valid: int,
    n_trials: int,
    mode: str,
) -> ModelMeasureConfig:
    """Broadcast fixed user-supplied macro projections over bootstrap resamples."""
    projection = config.macro_projection
    if projection is None or projection.ndim == 2:
        return config
    if projection.ndim != 3:
        raise ValueError("macro_projection must have shape (m,n) or (batch,m,n)")
    if mode == "pooled":
        if projection.shape[0] != 1:
            raise ValueError("pooled inference accepts one fixed macro projection")
        return replace(config, macro_projection=projection.expand(n_valid, -1, -1))
    if projection.shape[0] != n_trials:
        raise ValueError("independent inference requires one projection per trajectory")
    expanded = projection.unsqueeze(0).expand(n_valid, -1, -1, -1)
    return replace(config, macro_projection=expanded.reshape(n_valid * n_trials, *projection.shape[1:]))


def _flatten_tensor_measures(value: Any, prefix: str = "") -> dict[str, torch.Tensor]:
    """Flatten nested measure dictionaries while ignoring metadata and contexts."""
    output: dict[str, torch.Tensor] = {}
    if torch.is_tensor(value):
        if prefix:
            output[prefix] = value
        return output
    if isinstance(value, Mapping):
        for key, child in value.items():
            if key in {"context", "available", "not_available", "model_type"}:
                continue
            name = f"{prefix}.{key}" if prefix else str(key)
            output.update(_flatten_tensor_measures(child, name))
    return output


def _resolve_measure_names(
    available: Mapping[str, torch.Tensor],
    requested: str | Sequence[str],
) -> tuple[str, ...]:
    """Resolve exact paths or unique leaf-name aliases."""
    if requested == "all_compatible":
        return tuple(sorted(available))
    raw = (requested,) if isinstance(requested, str) else tuple(requested)
    resolved: list[str] = []
    for name in raw:
        if name in available:
            resolved.append(name)
            continue
        matches = [path for path in available if path.rsplit(".", 1)[-1] == name]
        if len(matches) == 1:
            resolved.append(matches[0])
            continue
        if not matches:
            raise ValueError(f"unknown or unavailable measure: {name}")
        raise ValueError(f"ambiguous measure name {name!r}; use one of {matches}")
    return tuple(dict.fromkeys(resolved))


def measure_confidence_intervals(
    X: np.ndarray | torch.Tensor,
    measures: str | Sequence[str] = "all_compatible",
    *,
    var: VAR | None = None,
    config: ModelMeasureConfig | None = None,
    method: ResamplingMethod = "residual_bootstrap",
    n_resamples: int = 1000,
    confidence: float = 0.95,
    seed: int | None = None,
    return_samples: bool = False,
) -> ConfidenceIntervalResult:
    r"""Estimate percentile confidence intervals from one shared VAR ensemble.

    The observed series is fitted once. Each bootstrap or parametric Monte Carlo
    realization is then generated from that fitted VAR and refitted at the same
    fixed order. All compatible primary measures are evaluated once on the
    resulting batched :class:`VARSystem`; selecting one or several ``measures``
    therefore does not repeat the resampling or VAR refits.

    Parameters
    ----------
    X
        Observations with shape ``(time, variables)`` or
        ``(batch, time, variables)``.
    measures
        ``"all_compatible"``, an exact flattened measure path such as
        ``"gaussian.o_information"``, a unique leaf alias such as
        ``"o_information"``, or a sequence of such names.
    var
        VAR estimator defining fixed order and fitting semantics. If omitted,
        ``VAR(order=1, mode="pooled")`` is used. The supplied estimator is copied
        before fitting and is not modified.
    config
        Primary-measure configuration. A supplied ``macro_projection`` is held
        fixed for dynamical-dependence inference. Projection optimization is
        never performed by this function.
    method
        ``"residual_bootstrap"`` resamples centered residual vectors with
        replacement. ``"parametric"`` draws Gaussian innovations from the fitted
        innovation covariance.
    n_resamples
        Number of requested synthetic VAR refits.
    confidence
        Central percentile confidence level in ``(0, 1)``.
    seed
        Optional Torch random seed.
    return_samples
        Whether to retain bootstrap measure samples in each result.

    Returns
    -------
    ConfidenceIntervalResult
        Point estimates, percentile limits, and resampling metadata.

    Notes
    -----
    Resampled unstable VARs are excluded explicitly and reported through
    ``n_failed``. In ``mode="independent"``, a resample is retained only when all
    trajectory-specific VAR fits are stable, preserving a common resample axis
    for every original trajectory.
    """
    if n_resamples < 2:
        raise ValueError("n_resamples must be at least two")
    if not 0 < confidence < 1:
        raise ValueError("confidence must lie strictly between zero and one")
    estimator = copy.deepcopy(VAR(order=1, mode="pooled") if var is None else var)
    if estimator.alpha != 0:
        raise ValueError("ARres inference currently requires an unregularized VAR")
    if estimator.solver == "lwr":
        raise ValueError("ARres inference currently supports OLS VAR estimators, not solver='lwr'")
    trials = _normalise_trials(estimator, X)
    estimator.fit(trials)
    residuals = _prediction_residuals(estimator, trials)
    generator = torch.Generator(device=trials.device)
    if seed is not None:
        generator.manual_seed(seed)
    innovations = _draw_innovations(
        residuals,
        estimator.noise_covariance_,
        mode=estimator.mode,
        method=method,
        n_resamples=n_resamples,
        generator=generator,
    )
    synthetic = _simulate_resamples(trials, estimator, innovations)
    coefficients, covariance = _batched_ols_refit(synthetic, estimator)
    valid = _stable_resample_mask(
        coefficients,
        n_resamples=n_resamples,
        n_trials=trials.shape[0],
        mode=estimator.mode,
    )
    n_valid = int(valid.sum().item())
    if n_valid < 2:
        raise RuntimeError("fewer than two stable resampled VARs remain")
    ensemble = _build_ensemble(
        coefficients,
        covariance,
        valid,
        n_resamples=n_resamples,
        n_trials=trials.shape[0],
        mode=estimator.mode,
    )
    original_system = build_var_system(estimator.coef_, estimator.noise_covariance_)
    measure_config = ModelMeasureConfig() if config is None else config
    original_flat = _flatten_tensor_measures(
        compute_all_model_measures(original_system, measure_config)
    )
    ensemble_measure_config = _ensemble_config(
        measure_config,
        n_valid=n_valid,
        n_trials=trials.shape[0],
        mode=estimator.mode,
    )
    ensemble_flat = _flatten_tensor_measures(
        compute_all_model_measures(ensemble, ensemble_measure_config)
    )
    names = _resolve_measure_names(original_flat, measures)
    missing = [name for name in names if name not in ensemble_flat]
    if missing:
        raise RuntimeError(f"measures unavailable on bootstrap ensemble: {missing}")
    alpha = (1.0 - confidence) / 2.0
    intervals: dict[str, MeasureInterval] = {}
    for name in names:
        estimate = original_flat[name]
        samples = ensemble_flat[name]
        if estimator.mode == "pooled":
            if samples.shape[0] != n_valid:
                raise RuntimeError(f"measure {name} does not preserve the VAR batch axis")
            estimate = estimate[0] if estimate.shape[:1] == (1,) else estimate
            sample_view = samples
        else:
            expected = n_valid * trials.shape[0]
            if samples.shape[0] != expected:
                raise RuntimeError(f"measure {name} does not preserve the VAR batch axis")
            sample_view = samples.reshape(n_valid, trials.shape[0], *samples.shape[1:])
        lower = torch.quantile(sample_view, alpha, dim=0)
        upper = torch.quantile(sample_view, 1.0 - alpha, dim=0)
        intervals[name] = MeasureInterval(
            estimate=estimate,
            lower=lower,
            upper=upper,
            samples=sample_view if return_samples else None,
            n_valid=n_valid,
        )
    return ConfidenceIntervalResult(
        intervals=intervals,
        method=method,
        confidence=confidence,
        n_resamples=n_resamples,
        n_valid=n_valid,
        n_failed=n_resamples - n_valid,
        seed=seed,
        var_order=estimator.order,
        fit_mode=estimator.mode,
    )


__all__ = [
    "ConfidenceIntervalResult",
    "MeasureInterval",
    "ResamplingMethod",
    "measure_confidence_intervals",
]
